/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as InstructorIndexRouteImport } from './routes/instructor/index'
import { Route as InstructorSessionRouteImport } from './routes/instructor/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorSessionRoute = InstructorSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => InstructorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/how-to-play': typeof HowToPlayRoute
  '/instructor': typeof InstructorRouteWithChildren
  '/join': typeof JoinRoute
  '/play': typeof PlayRoute
  '/practice': typeof PracticeRoute
  '/instructor/session': typeof InstructorSessionRoute
  '/instructor/': typeof InstructorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/how-to-play': typeof HowToPlayRoute
  '/join': typeof JoinRoute
  '/play': typeof PlayRoute
  '/practice': typeof PracticeRoute
  '/instructor/session': typeof InstructorSessionRoute
  '/instructor': typeof InstructorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/how-to-play': typeof HowToPlayRoute
  '/instructor': typeof InstructorRouteWithChildren
  '/join': typeof JoinRoute
  '/play': typeof PlayRoute
  '/practice': typeof PracticeRoute
  '/instructor/session': typeof InstructorSessionRoute
  '/instructor/': typeof InstructorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefing'
    | '/how-to-play'
    | '/instructor'
    | '/join'
    | '/play'
    | '/practice'
    | '/instructor/session'
    | '/instructor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefing'
    | '/how-to-play'
    | '/join'
    | '/play'
    | '/practice'
    | '/instructor/session'
    | '/instructor'
  id:
    | '__root__'
    | '/'
    | '/briefing'
    | '/how-to-play'
    | '/instructor'
    | '/join'
    | '/play'
    | '/practice'
    | '/instructor/session'
    | '/instructor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  HowToPlayRoute: typeof HowToPlayRoute
  InstructorRoute: typeof InstructorRouteWithChildren
  JoinRoute: typeof JoinRoute
  PlayRoute: typeof PlayRoute
  PracticeRoute: typeof PracticeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/session': {
      id: '/instructor/session'
      path: '/session'
      fullPath: '/instructor/session'
      preLoaderRoute: typeof InstructorSessionRouteImport
      parentRoute: typeof InstructorRoute
    }
  }
}

interface InstructorRouteChildren {
  InstructorSessionRoute: typeof InstructorSessionRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorSessionRoute: InstructorSessionRoute,
  InstructorIndexRoute: InstructorIndexRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  HowToPlayRoute: HowToPlayRoute,
  InstructorRoute: InstructorRouteWithChildren,
  JoinRoute: JoinRoute,
  PlayRoute: PlayRoute,
  PracticeRoute: PracticeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
